source 'https://rubygems.org'

gem 'selenium-webdriver', '~> 2.44.0'
gem 'rspec-expectations'
gem 'json'
gem 'rspec'
gem 'rest-client'
gem 'browsermob-proxy'
gem 'parallel_tests'
gem 'ruby-gmail'
#gem 'pry'
#gem 'pry-debugger'
gem 'typhoeus'
gem 'rspec_junit_formatter'
gem 'ruby-jmeter'
gem 'recursive-open-struct'
gem 'uuid'
